repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
        exclude: |
          (?x)^(
            package.json|
            package-lock.json
          )$
      - id: check-toml
      - id: check-yaml
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
  - repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v1.65.0 # 使用するバージョンを固定
    hooks:
      - id: oxlint # リポジトリ側で定義済みのフックIDを指定

  - repo: local
    hooks:
      - id: oxfmt
        name: oxfmt (md/mdx) # 実行時の表示名
        entry: npx oxfmt --write # 実行するコマンド
        language: node # ローカルの実行環境をそのまま使う
        files: \.(md|mdx)$ # 対象ファイルを正規表現で絞り込む
