
[env]
_.path = ['{{config_root}}/node_modules/.bin']

# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Set up the path for node module binaries
BIN_PATH = "{{ config_root }}/node_modules/.bin"

NODE_ENV = "{{ env.NODE_ENV | default(value='development') }}"


[tools]
"npm:npm" = "latest"
pre-commit = "latest"

# [tasks.install]
# alias = "i"
# description = "Install npm dependencies"
# run = "npm install"

# [tasks.start]
# alias = "s"
# description = "Start the development server"
# run = "npm run dev"

# [tasks.lint]
# alias = "l"
# description = "Run ESLint"
# run = "eslint src/"

# [tasks.test]
# description = "Run tests"
# alias = "t"
# run = "jest"

# [tasks.build]
# description = "Build the project"
# alias = "b"
# run = "npm run build"

# [tasks.info]
# description = "Print project information"
# run = '''
# echo "Project: $PROJECT_NAME"
# echo "NODE_ENV: $NODE_ENV"
# '''


# MISE_ORIGINAL_CWD: The original working directory from where the task was run.
# MISE_CONFIG_ROOT: The directory containing the mise.toml file where the task was defined or if the config path is something like ~/src/myproj/.config/mise.toml, it will be ~/src/myproj.
# MISE_PROJECT_ROOT: The root of the project that defines the task. For monorepo subproject tasks this is the subproject's directory and is stable regardless of the directory the task is invoked from.
# MISE_MONOREPO_ROOT: The root of the monorepo (the directory containing the config with experimental_monorepo_root = true). Only set inside a monorepo.
# MISE_TASK_NAME: The name of the task being run.
# MISE_TASK_DIR: The directory containing the task script.
# MISE_TASK_FILE: The full path to the task script.
