name: blog-build-actions
run-name: ${{ github.actor }} is building on GitHub Actions
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # このリポジトリをチェックアウトしてー
      - uses: actions/checkout@v3

      # push先もチェックアウトしてー
      - name: Checkout github.io repo
        uses: actions/checkout@v3
        with:
          repository: tetsuyainfra/tetsuyainfra.github.io
          path: public
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Node.jsをセットアップ
      - uses: actions/setup-node@v3
        with:
          # package.json -> engines -> nodeからバージョンを取得
          node-version-file: 'package.json'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v3
        with:
          path: |
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Github Pages Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          cd public
          ls -la /home/runner/work/_temp
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          echo "Will Push"
          git push